<a href="https://colab.research.google.com/github/saikiranmuthuluri/Audio-to-text-by-Hugging-face/blob/main/Hugging_face_Audio_to_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
# Installing transformers
!pip install transformers

In [71]:
# Importing pipeline
from transformers import pipeline

In [72]:
# Checking transformers version
import transformers
print(transformers.__version__)

4.47.1


In [73]:
# Installing required libraries
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np

In [74]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.


In [75]:
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [76]:
# Loading Audio file
audio,sampling_rate=librosa.load("/content/OSR_us_000_0019_8k.wav",sr=16000)

In [77]:
audio,sampling_rate

(array([0.00120451, 0.00148785, 0.00135475, ..., 0.00450337, 0.00399466,
        0.00207901], dtype=float32),
 16000)

In [78]:
# Displaying a audio
display.Audio("/content/OSR_us_000_0019_8k.wav",autoplay=True)

In [79]:
input_values = tokenizer(audio,return_tensor = "pt").input_values

In [80]:
input_values

array([[0.04036863, 0.04940724, 0.0451613 , ..., 0.14560232, 0.12937458,
        0.06826542]])

In [81]:
logits = model(torch.tensor(input_values).type(torch.float32)).logits

In [82]:
logits

tensor([[[ 15.2546, -26.7766, -26.4221,  ...,  -6.5722,  -7.6135,  -7.6230],
         [ 15.3286, -26.8003, -26.4500,  ...,  -6.4342,  -7.6222,  -7.5502],
         [ 15.4317, -26.7946, -26.4397,  ...,  -6.3969,  -7.6179,  -7.4969],
         ...,
         [ 15.1540, -26.7857, -26.4704,  ...,  -6.4024,  -7.8812,  -7.1726],
         [ 15.0732, -26.1916, -25.8387,  ...,  -5.9347,  -7.2002,  -7.2858],
         [ 15.1791, -26.5850, -26.2406,  ...,  -6.3434,  -7.6570,  -7.4576]]],
       grad_fn=<ViewBackward0>)

In [83]:
predicted_ids = torch.argmax(logits,dim=-1)

In [84]:
# Tokenizing the words
transcriptions = tokenizer.decode(predicted_ids[0])

In [85]:
# Printing the words
transcriptions

'THE KING RULED THE STATE IN EARLY DAYS THE SHIP WAS TORN APART ON THE SHARP REEF SICKNESS KEPT HIM HOME THE THIRD WEEK THE WIDE ROAD SHIMMERED IN THE HOT SUN THE LAZY COW LAY IN THE COOL GRASS LIFT THE SWARE STONE OVER THE SENCE THE ROPE OTE BYIN THE SEVEN BOOKS AT ONCE HOP OVER THE FENCE AND PLUNGE IN THE FRIENDLY GANG LEFT THE DRUG STORE MESH WIRE KEEPS CHICKS INSIDE'